application: webrobots
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
# - appstats: on
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/vnd.microsoft.icon

- url: /static
  static_dir: static

- url: /task/.*
  script: backend.application
  login: admin

- url: /cron/.*
  script: backend.application
  login: admin

- url: /.*
  script: frontend.application


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3.5"
